// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypdvbrqijutxiwxiicev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZHZicnFpanV0eGl3eGlpY2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDIwMDIsImV4cCI6MjA1NDE3ODAwMn0.r48PKKAXw5eOPwLfnFIwXPUTHlWaoSPZeshmA9nU0vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);